name: Publish packages to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.post[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  sdist-purewheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install build
    - name: Create sdist and pure-Python wheel
      run: python -m build .
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*

  publish:
    needs:
      - sdist-purewheel
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Download generated packaging artifacts
      uses: actions/download-artifact@v7
    - name: Move the packages to dist/
      run: |
        mkdir -p dist
        mv */*.whl */*.tar.gz dist 2>/dev/null || true
    - name: Upload packages
      uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: Create a GitHub release
    needs:
      - sdist-purewheel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - id: changelog
      uses: agronholm/release-notes@v1
      with:
        path: docs/versionhistory.rst
    - uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
